version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db
  
  web:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - api

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
